### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Darkhell101** [OrangeX4/Latex-Sympy-Calculator#11]
1. \int_{-1}^{1} \ln^{2}{(x+2)} dx = - \ln{(729)} + 3 \ln{(3)}^{2} + 4 ,But the correct answer is - \ln{(729)} + 3 \ln^{2}{(3)} + 4. Position of ^{2} is wrong.
2. nonlinsolve([x**2+y**3-2, x**3+y**3],[x,y]) when press c+s+alt+p, it does not work.
3. when i try to define a value(y = 1) by c+s+alt+D, it does not work, too.
thanks for your wonderful work!

**Comment by OrangeX4** [comment]
1. The problem is caused by the `latex()` function in sympy, and i don't have any idea to fix it temporarily.
2. You should use `nonlinsolve([x ** 2 + y ** 3 - 2, x ** 3 + y ** 3],[x,y])`, where the `x ** 2` is the syntax of power of  python.
3. It works. After you define `y = 1`, you can use it by `c+s+alt+ E / R / N`. for example `2y` will be convert to `2`.

**Comment by Darkhell101** [comment]
2. I expected something else here nonlinsolve([x ** 2 + y ** 3 - 2, x ** 3 + y ** 3],[x,y]) ~~~~~~~~~~~~~~~~^ an info to me
3. i select (y = 1) and press c+s+alt+D, next select (3y) and press c+s+alt+E. It also return 3 y
y = 1 
3y = 3 y
In fact, if i try to define a matrix like X \in \mathbb{R}^{n \times m}, it works. I don't know why

**Comment by OrangeX4** [comment]
2. You should use `c+s+alt+P` instead of `c+s+alt+ E / R / N`.
3. You should select `y = 1` instead of `(y = 1)`.

**Comment by OrangeX4** [comment]
If there still are problems, you can update by `pip install -upgrade latex2sympy2` and the newest version is `1.7.4`. And then reboot your computer.

**Comment by Darkhell101** [comment]
thanks for your advice

**Comment by Darkhell101** [comment]
I know why problem 3 happens, c+s+alt+D is not useful for my settings. I change it into c+s+alt+M
